apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-cert-manager-solver
  namespace: {{ .Values.istioNamespace }}
  labels:
    app: {{ .Values.name }}-cert-manager-solver
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: http
  selector:
    acme.cert-manager.io/http01-solver: "true"