
name: "principal"
hosts:
  - "administrabien.cl"
istioNamespace: "istio-ingress"
gateways:
  - "istio-ingress/istioingress-gateway"
defaultPort: "8080"
expose:
  - prefix: /
    exact:
    uriRewrite: /
    serviceName: "my-service"
    overrideSvc: "my-service-real-name"
    overrideNamespace: "my-real-namespace"
    port: "0"