
name: "principal"
hosts:
  - "administrabien.cl"
gateways:
  - "istio-ingress/istioingress-gateway"
defaultPort: "8080"
expose:
  - prefix: /
    reRewrite: /
    serviceName: "my-service"
    port: "0"